module.exports = [
  "Harina de trigo",
  "Harina para tortas",
  "Pasta para sopa",
  "Cereal para desayuno",
  "Cereal alimento para bebé",
  "Avena hojuelas",
  "Avena molida",
  "Cebada",
  "Cuchuco de maíz",
  "Cuchuco de trigo",
  "Galletas dulces",
  "Galletas integrales",
  "Arepa precocida",
  "Ajo",
  "Cilantro",
  "Frijol tarro",
  "Arveja tarro",
  "Melocotones o variedad disponible en conserva",
  "Carne de cerdo con hueso",
  "Pollo despresado por libra",
  "Pescado enlatado",
  "Crema de leche",
  "Mantequilla",
  "Suero",
  "Aceite de girasol",
  "Manteca vegetal",
  "Café instantáneo",
  "Chocolate instantáneo",
  "Cremas",
  "Mayonesa",
  "Mostaza",
  "Gelatina o flan",
  "Papas fritas",
  "Mermeladas",
  "Jugos procesados",
  "Jugos instantáneos o en polvo",
  "Maltas",
  "Agua mineral",
  "Almuerzo especial o a la carta",
  "Pizza",
  "Combos – comidas rápidas",
  "Arepas rellenas de algo",
  "Helado de crema",
  "Ensalada de frutas",
];
